# Generated by Django 4.2.2 on 2023-11-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('P1', 'Priority 1'), ('P2', 'Priority 2'), ('P3', 'Priority 3'), ('P4', 'Priority 4')], default='P1', max_length=2),
        ),
    ]
